import { Router } from "express";
import { contractorRouter } from "./contractorRouter";
import { moverRouter } from "./moverRouter";
import { customerRouter } from "./customerRouter";
import { employeeRouter } from "./employeeRouter";
import { agriculturalSeasonRouter } from "./agriculturalSeasonRouter";
import { fuelTankRouter } from "./fuelTankRouter";
import { materialRouter } from "./materialRouter";
import { baleRouter } from "./baleRouter";
import { operationRouter } from "./operationRouter";
import { plotRouter } from "./plotRouter";
import { tractorRouter } from "./tractorRouter";
import { supplierRouter } from "./supplierRouter";
import { materialPurchaseTrackingRouter } from "./materialPurchaseTrackingRouter";
import { materialUsageTrackingRouter } from "./materialUsageTrackingRouter";
import { operationTrackingRouter } from "./operationTrackingRouter";
import { fuelOperationTrackingRouter } from "./fuelOperationTrackingRouter";
import { baleOrderTrackingRouter } from "./baleOrderTrackingRouter";
import { contractorTrackingRouter } from "./contractorTrackingRouter";
import { transportTrackingRouter } from "./transportTrackingRouter";
import { transportChargeStateRouter } from "./transportChargeStateRouter";
import { customerBillingTrackingRouter } from "./customerBillingTrackingRouter";

export const apiRouter = Router();

apiRouter.use("/contractors", contractorRouter);
apiRouter.use("/movers", moverRouter);
apiRouter.use("/suppliers", supplierRouter);
apiRouter.use("/customers", customerRouter);
apiRouter.use("/employees", employeeRouter);
apiRouter.use("/tractors", tractorRouter);
apiRouter.use("/operations", operationRouter);
apiRouter.use("/materials", materialRouter);
apiRouter.use("/bales", baleRouter);
apiRouter.use("/plots", plotRouter);
apiRouter.use("/agriculturalSeasons", agriculturalSeasonRouter);
apiRouter.use("/fuelTanks", fuelTankRouter);
apiRouter.use("/materialPurchaseTrackings", materialPurchaseTrackingRouter);
apiRouter.use("/material-purchase-trackings", materialPurchaseTrackingRouter);
apiRouter.use("/materialUsageTrackings", materialUsageTrackingRouter);
apiRouter.use("/material-usage-trackings", materialUsageTrackingRouter);
apiRouter.use("/operationsTrackings", operationTrackingRouter);
apiRouter.use("/operations-trackings", operationTrackingRouter);
apiRouter.use("/fuelOperationsTrackings", fuelOperationTrackingRouter);
apiRouter.use("/fuel-operations-trackings", fuelOperationTrackingRouter);
apiRouter.use("/baleOrderTrackings", baleOrderTrackingRouter);
apiRouter.use("/bale-order-trackings", baleOrderTrackingRouter);
apiRouter.use("/contractorTrackings", contractorTrackingRouter);
apiRouter.use("/contractor-trackings", contractorTrackingRouter);
apiRouter.use("/transportTrackings", transportTrackingRouter);
apiRouter.use("/transport-trackings", transportTrackingRouter);
apiRouter.use("/transportChargeState", transportChargeStateRouter);
apiRouter.use("/transport-charge-state", transportChargeStateRouter);
apiRouter.use("/customerBillingTrackings", customerBillingTrackingRouter);
apiRouter.use("/customer-billing-trackings", customerBillingTrackingRouter);
