import { Router } from "express";
import { requireAdmin, requireAuth, requireAdminForWrite } from "../middleware/authMiddleware";
import { authRouter } from "./authRouter";
import { contractorRouter } from "./contractorRouter";
import { moverRouter } from "./moverRouter";
import { customerRouter } from "./customerRouter";
import { employeeRouter } from "./employeeRouter";
import { agriculturalSeasonRouter } from "./agriculturalSeasonRouter";
import { fuelTankRouter } from "./fuelTankRouter";
import { materialRouter } from "./materialRouter";
import { baleRouter } from "./baleRouter";
import { operationRouter } from "./operationRouter";
import { plotRouter } from "./plotRouter";
import { tractorRouter } from "./tractorRouter";
import { supplierRouter } from "./supplierRouter";
import { materialPurchaseTrackingRouter } from "./materialPurchaseTrackingRouter";
import { materialUsageTrackingRouter } from "./materialUsageTrackingRouter";
import { operationTrackingRouter } from "./operationTrackingRouter";
import { fuelOperationTrackingRouter } from "./fuelOperationTrackingRouter";
import { baleOrderTrackingRouter } from "./baleOrderTrackingRouter";
import { contractorTrackingRouter } from "./contractorTrackingRouter";
import { transportTrackingRouter } from "./transportTrackingRouter";
import { transportGlobalChargeRouter } from "./transportGlobalChargeRouter";
import { customerBillingTrackingRouter } from "./customerBillingTrackingRouter";
import { monthlyReportRouter } from "./monthlyReportRouter";
import { summariesRouter } from "./summariesRouter";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use(requireAuth);

apiRouter.use("/contractors", requireAdmin, contractorRouter);
apiRouter.use("/movers", requireAdmin, moverRouter);
apiRouter.use("/suppliers", requireAdmin, supplierRouter);
apiRouter.use("/customers", requireAdmin, customerRouter);
apiRouter.use("/employees", requireAdmin, employeeRouter);
apiRouter.use("/tractors", requireAdminForWrite, tractorRouter);
apiRouter.use("/operations", requireAdminForWrite, operationRouter);
apiRouter.use("/materials", requireAdminForWrite, materialRouter);
apiRouter.use("/bales", requireAdmin, baleRouter);
apiRouter.use("/plots", requireAdminForWrite, plotRouter);
apiRouter.use("/agriculturalSeasons", requireAdmin, agriculturalSeasonRouter);
apiRouter.use("/fuelTanks", requireAdminForWrite, fuelTankRouter);
apiRouter.use("/materialPurchaseTrackings", requireAdmin, materialPurchaseTrackingRouter);
apiRouter.use("/material-purchase-trackings", requireAdmin, materialPurchaseTrackingRouter);
apiRouter.use("/materialUsageTrackings", materialUsageTrackingRouter);
apiRouter.use("/material-usage-trackings", materialUsageTrackingRouter);
apiRouter.use("/operationsTrackings", operationTrackingRouter);
apiRouter.use("/operations-trackings", operationTrackingRouter);
apiRouter.use("/fuelOperationsTrackings", fuelOperationTrackingRouter);
apiRouter.use("/fuel-operations-trackings", fuelOperationTrackingRouter);
apiRouter.use("/baleOrderTrackings", requireAdmin, baleOrderTrackingRouter);
apiRouter.use("/bale-order-trackings", requireAdmin, baleOrderTrackingRouter);
apiRouter.use("/contractorTrackings", requireAdmin, contractorTrackingRouter);
apiRouter.use("/contractor-trackings", requireAdmin, contractorTrackingRouter);
apiRouter.use("/transportTrackings", requireAdmin, transportTrackingRouter);
apiRouter.use("/transport-trackings", requireAdmin, transportTrackingRouter);
apiRouter.use("/transportGlobalCharges", requireAdmin, transportGlobalChargeRouter);
apiRouter.use("/transport-global-charges", requireAdmin, transportGlobalChargeRouter);
apiRouter.use("/customerBillingTrackings", requireAdmin, customerBillingTrackingRouter);
apiRouter.use("/customer-billing-trackings", requireAdmin, customerBillingTrackingRouter);
apiRouter.use("/monthly-report", requireAdmin, monthlyReportRouter);
apiRouter.use("/monthly-reports", requireAdmin, monthlyReportRouter);
apiRouter.use("/summaries", requireAdmin, summariesRouter);
